name: Build Project

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  
jobs:
  Release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Build
        shell: bash
        run: '"/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe" -property:Configuration=Release'
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Release
          path: |
            ./Release/AmongUsMenu.dll
            ./LICENSE
  
  Release_Version:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Build
        shell: bash
        run: '"/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe" -property:Configuration=Release_Version'
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Release_Version
          path: |
            ./Release_Version/version.dll
            ./LICENSE
  Debug:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Build
        shell: bash
        run: '"/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe" -property:Configuration=Debug'
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Debug
          path: |
            ./Debug/AmongUsMenu.dll
            ./LICENSE
  
  Debug_Version:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Build
        shell: bash
        run: '"/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe" -property:Configuration=Debug_Version'
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Debug_Version
          path: | 
            ./Debug_Version/version.dll
            ./LICENSE
  
